title: "Yunzhi (Ariel) Zheng"
email: "yzheng9@fsu.edu"
description: "Couple Relationships · Mindfulness · Dyadic Processes · Machine Learning for Psychotherapy"
github_username: yunzhiarielzheng

url: "https://yunzhiarielzheng.github.io"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - research.md
  - publications.md
  - teaching.md
  - clinical.md

author:
  Yunzhi (Ariel) Zheng
  Doctoral Candidate · Marriage and Family Therapy · Florida State University
  Tallahassee, FL
  https://scholar.google.com/citations?user=Jl9si-AAAAAJ&hl=en&oi=ao




